services:
  flask-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: soka_server
    ports:
      - "${VM_PORT}:5000"
    env_file:
      - .env
    restart: always